#Config\u6587\u4EF6
#Mon Jan 12 01:00:57 CST 2026
outputDir=D\:\\exe4j\\excel2word
templatePrefix=${
templateSuffix=}
templateFile=D\:\\exe4j\\excel2word\\template.docx
inputDir=D\:\\exe4j\\excel2word

